spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/marketplace
    username: ecocycle
    password: ecocycle
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

marketplace:
  base-url: http://localhost:8081

users:
  base-url: http://localhost:8083

jwt:
  secret: my-super-long-secret-key-ecocycle-123456789   # keep same across services
  expiration: 86400000   # 1 day in ms